version: 1.0
phases:
  install:
     runtime-versions:
        java: openjdk8
     build:
      commands:
         - aws cloudformation package --template-file samTemplate.yaml --s3-bucket dev-rs-lambda --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml