AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  LambdaFunctionHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.test.pipe.pipe.LambdaFunctionHandler
      Runtime: java8
      CodeUri: ./com/test/pipe/pipe
      Description: 'Lambda function for CD Demo'
      MemorySize: 256
      Timeout: 30
      Role: 'arn:aws:iam::596911091655:role/LambdaRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
        REGION: us-west-2